name: Run Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    env:
      DOTNET_ROOT: C:\Program Files\dotnet

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '9.0.x'  # Specify the required .NET version
        architecture: 'x64'      # Specify the correct architecture

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Run tests
      run: dotnet test --no-restore --verbosity normal
